/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Graph2DTest.java
 *
 * Created on 25.12.2011, 18:22:07
 */
package graphtest;

import Figures.Point;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Yan
 */
public class Graph2DTest extends javax.swing.JFrame {

    /** Creates new form Graph2DTest */
    public Graph2DTest() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pannel = new DrawPannel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_File = new javax.swing.JMenu();
        jMenuItem_Open = new javax.swing.JMenuItem();
        jMenuItem_Save = new javax.swing.JMenuItem();
        jMenu_Graph = new javax.swing.JMenu();
        jMenuItem_AddNode = new javax.swing.JMenuItem();
        jMenuItem_AddEdge = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_DeleteGrapg = new javax.swing.JMenuItem();
        jCheckBoxMenuItem_ShowMap = new javax.swing.JCheckBoxMenuItem();
        jMenu_SearchAWay = new javax.swing.JMenu();
        jMenuItem_SetStartVertex = new javax.swing.JMenuItem();
        jMenuItem_FindWayTo = new javax.swing.JMenuItem();
        jMenu_Assistance = new javax.swing.JMenu();
        jMenuItem_Help = new javax.swing.JMenuItem();
        jMenuItem_About = new javax.swing.JMenuItem();
        jMenuItem_SampleGraph = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Graph2D Test");
        setResizable(false);

        Pannel.setBackground(new java.awt.Color(255, 255, 255));
        Pannel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PannelMousePressed(evt);
            }
        });
        Pannel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PannelMouseDragged(evt);
            }
        });

        javax.swing.GroupLayout PannelLayout = new javax.swing.GroupLayout(Pannel);
        Pannel.setLayout(PannelLayout);
        PannelLayout.setHorizontalGroup(
            PannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 958, Short.MAX_VALUE)
        );
        PannelLayout.setVerticalGroup(
            PannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );

        jMenu_File.setText("File");

        jMenuItem_Open.setText("Open");
        jMenuItem_Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_OpenActionPerformed(evt);
            }
        });
        jMenu_File.add(jMenuItem_Open);

        jMenuItem_Save.setText("Save");
        jMenuItem_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_SaveActionPerformed(evt);
            }
        });
        jMenu_File.add(jMenuItem_Save);

        jMenuBar1.add(jMenu_File);

        jMenu_Graph.setText("Graph");

        jMenuItem_AddNode.setText("Add node");
        jMenuItem_AddNode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_AddNodeActionPerformed(evt);
            }
        });
        jMenu_Graph.add(jMenuItem_AddNode);

        jMenuItem_AddEdge.setText("Add edge");
        jMenuItem_AddEdge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_AddEdgeActionPerformed(evt);
            }
        });
        jMenu_Graph.add(jMenuItem_AddEdge);
        jMenu_Graph.add(jSeparator3);

        jMenuItem_DeleteGrapg.setText("Delete graph");
        jMenuItem_DeleteGrapg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_DeleteGrapgActionPerformed(evt);
            }
        });
        jMenu_Graph.add(jMenuItem_DeleteGrapg);

        jCheckBoxMenuItem_ShowMap.setText("Show map");
        jCheckBoxMenuItem_ShowMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem_ShowMapActionPerformed(evt);
            }
        });
        jMenu_Graph.add(jCheckBoxMenuItem_ShowMap);

        jMenuBar1.add(jMenu_Graph);

        jMenu_SearchAWay.setText("Search a way");

        jMenuItem_SetStartVertex.setText("Set start vertex");
        jMenuItem_SetStartVertex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_SetStartVertexActionPerformed(evt);
            }
        });
        jMenu_SearchAWay.add(jMenuItem_SetStartVertex);

        jMenuItem_FindWayTo.setText("Find way to");
        jMenuItem_FindWayTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_FindWayToActionPerformed(evt);
            }
        });
        jMenu_SearchAWay.add(jMenuItem_FindWayTo);

        jMenuBar1.add(jMenu_SearchAWay);

        jMenu_Assistance.setText("Assistance");

        jMenuItem_Help.setText("Help");
        jMenuItem_Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_HelpActionPerformed(evt);
            }
        });
        jMenu_Assistance.add(jMenuItem_Help);

        jMenuItem_About.setText("About");
        jMenuItem_About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_AboutActionPerformed(evt);
            }
        });
        jMenu_Assistance.add(jMenuItem_About);

        jMenuItem_SampleGraph.setText("Sample graph");
        jMenuItem_SampleGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_SampleGraphActionPerformed(evt);
            }
        });
        jMenu_Assistance.add(jMenuItem_SampleGraph);

        jMenuBar1.add(jMenu_Assistance);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PannelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PannelMousePressed
        Point mouse = new Point(evt.getX(), evt.getY());
        ProcessingFrame.chooseVertex(mouse);
        if (evt.getClickCount() >= 2) {
            ProcessingFrame.renameVertex();
            repaint();
        }
    }//GEN-LAST:event_PannelMousePressed

    private void PannelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PannelMouseDragged
        Point mouse = new Point(evt.getX(), evt.getY());
        ProcessingFrame.moveVertex(mouse);
        repaint();
    }//GEN-LAST:event_PannelMouseDragged

    private void jMenuItem_SetStartVertexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_SetStartVertexActionPerformed
        ProcessingFrame.setStartVertex();
        repaint();
    }//GEN-LAST:event_jMenuItem_SetStartVertexActionPerformed

    private void jMenuItem_FindWayToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_FindWayToActionPerformed
        ProcessingFrame.findShortesWay();
        repaint();
    }//GEN-LAST:event_jMenuItem_FindWayToActionPerformed

    private void jMenuItem_OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_OpenActionPerformed
        JFileChooser chooser = new JFileChooser();
        String fileName = "";

        //The program work with files: .java, .cpp, .txt.
        FileNameExtensionFilter filter = new FileNameExtensionFilter("txt", "graph");
        chooser.setFileFilter(filter);
        chooser.setCurrentDirectory(new File("."));
        chooser.setAcceptAllFileFilterUsed(false);
        //Dialog for choosing a file.
        int result = chooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION)
            fileName = chooser.getSelectedFile().getPath();
        if (fileName == null)
            return;
        ProcessingFrame.readGraph(fileName);
        repaint();
    }//GEN-LAST:event_jMenuItem_OpenActionPerformed

    private void jMenuItem_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_SaveActionPerformed
        JFileChooser chooser = new JFileChooser();
        String fileName = "";

        //The program work with files: .java, .cpp, .txt.
        FileNameExtensionFilter filter = new FileNameExtensionFilter("txt", "graph");
        chooser.setFileFilter(filter);
        chooser.setCurrentDirectory(new File("."));
        chooser.setAcceptAllFileFilterUsed(false);
        //Dialog for choosing a file.
        int result = chooser.showSaveDialog(this);

        if (result == JFileChooser.APPROVE_OPTION)
            fileName = chooser.getSelectedFile().getPath();
        if (fileName == null)
            return;
        ProcessingFrame.writeGraph(fileName);
    }//GEN-LAST:event_jMenuItem_SaveActionPerformed

    private void jMenuItem_AddNodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_AddNodeActionPerformed
        ProcessingFrame.addNode();
        repaint();
    }//GEN-LAST:event_jMenuItem_AddNodeActionPerformed

    private void jMenuItem_DeleteGrapgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_DeleteGrapgActionPerformed
        ProcessingFrame.deleteGraph();
        repaint();
    }//GEN-LAST:event_jMenuItem_DeleteGrapgActionPerformed

    private void jMenuItem_AddEdgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_AddEdgeActionPerformed
        ProcessingFrame.addEdge();
        repaint();
    }//GEN-LAST:event_jMenuItem_AddEdgeActionPerformed

    private void jMenuItem_HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_HelpActionPerformed
        ProcessingFrame.help();
    }//GEN-LAST:event_jMenuItem_HelpActionPerformed

    private void jMenuItem_AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_AboutActionPerformed
        ProcessingFrame.about();
    }//GEN-LAST:event_jMenuItem_AboutActionPerformed

    private void jMenuItem_SampleGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_SampleGraphActionPerformed
        ProcessingFrame.sampleGraph();
    }//GEN-LAST:event_jMenuItem_SampleGraphActionPerformed

    private void jCheckBoxMenuItem_ShowMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem_ShowMapActionPerformed
        boolean flag = jCheckBoxMenuItem_ShowMap.getState();
        ProcessingFrame.showMap(flag);
        repaint();
    }//GEN-LAST:event_jCheckBoxMenuItem_ShowMapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Graph2DTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Graph2DTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Graph2DTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Graph2DTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                Toolkit kit = Toolkit.getDefaultToolkit();
                Dimension size = kit.getScreenSize();
                int maxX = size.width;
                int maxY = size.height;
                javax.swing.JFrame main =  new Graph2DTest();
                main.setBounds(0, 0, maxX, maxY);
                main.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pannel;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem_ShowMap;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_About;
    private javax.swing.JMenuItem jMenuItem_AddEdge;
    private javax.swing.JMenuItem jMenuItem_AddNode;
    private javax.swing.JMenuItem jMenuItem_DeleteGrapg;
    private javax.swing.JMenuItem jMenuItem_FindWayTo;
    private javax.swing.JMenuItem jMenuItem_Help;
    private javax.swing.JMenuItem jMenuItem_Open;
    private javax.swing.JMenuItem jMenuItem_SampleGraph;
    private javax.swing.JMenuItem jMenuItem_Save;
    private javax.swing.JMenuItem jMenuItem_SetStartVertex;
    private javax.swing.JMenu jMenu_Assistance;
    private javax.swing.JMenu jMenu_File;
    private javax.swing.JMenu jMenu_Graph;
    private javax.swing.JMenu jMenu_SearchAWay;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
